name: Run Script

on:
  schedule:
    - cron: '0 14 * * 1'  # Agendado para rodar toda segunda-feira às 11 da manhã no horário local (UTC-3)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      run: python main.py
