name: Scraping Weekly

on:
  schedule:
    - cron: '0 10 * * 1' # Segunda-feira às 10:00
  workflow_dispatch: # Permitir execução manual

jobs:
  scrape_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 


      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run scraping script
        run: npm run scrape

      - name: Commit scraped images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Weekly scraping: updated images" || echo "No changes to commit."
          git push origin HEAD:${{ github.ref_name }}

